version: '3.3'
services:
  zookeeper:
    image: ogergardt/zookeeper
    ports:
        - "2181:2181"
        - "2888:2888"
        - "3888:3888"
  kafka:
    image: ogergardt/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092-9094"
    environment:
      KAFKA_LOG_DIRS: /kafka
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_HOURS: "168"
      KAFKA_LOG_RETENTION_BYTES: "100000000"
      KAFKA_ZOOKEEPER_CONNECT:  zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

